services:
  - type: web
    name: crypto-api
    env: python
    region: oregon
    buildCommand: ""
    startCommand: "python init_db.py && python app.py"
    #startCommand: |
    #  python init_db.py && python app.py
    envVars:
      - key: PORT
        value: 5000
    plan: free
    rootDir: backend
